import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.161.0/build/three.module.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v)),smooth=t=>t*t*(3-2*t);
const projects=[['Sprocket Central — Customer & Sales Intelligence','01','Customer segmentation, sales performance and insight discovery.','Power BI · Segmentation · Analysis'],['Credit Card Transaction Analysis','02','Transaction patterns, customer behavior and financial performance.','Power BI · SQL · Data Modeling'],['COVID-19 Data Analysis','03','A visual exploration of global COVID-19 trends and impact.','Power BI · Trends · Visualization'],['Company Attrition Analytics','04','Workforce attrition patterns and people-focused business insights.','Power BI · HR Analytics · Insights'],['Data-Driven Sales Analysis','05','Sales performance analysis focused on commercial decision-making.','Power BI · Forecasting · KPI'],['Google Play Store Apps Analysis','06','App ecosystem, category and performance analysis.','Power BI · Data Cleaning · App Analytics'],['Sales Data Analysis','07','Performance trends and actionable business metrics.','Power BI · Excel · Data Analysis']];
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(38,innerWidth/innerHeight,.1,100);camera.position.set(0,0,10.8);
const renderer=new THREE.WebGLRenderer({canvas:$('#webgl'),antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.55;scene.background=new THREE.Color(0x01040a);
scene.add(new THREE.AmbientLight(0x496175,.25));const cyan=new THREE.PointLight(0x43efff,32,12);cyan.position.set(2.5,2.5,3);scene.add(cyan);const violet=new THREE.PointLight(0x895dff,25,11);violet.position.set(-2,-1.5,2);scene.add(violet);const coreLight=new THREE.PointLight(0xaaffff,26,6);coreLight.position.set(0,0,1.7);scene.add(coreLight);
const root=new THREE.Group();const core=new THREE.Group();scene.add(root);root.add(core);
const outer=new THREE.Mesh(new THREE.SphereGeometry(1.42,64,64),new THREE.MeshPhysicalMaterial({color:0x04141c,metalness:.7,roughness:.12,clearcoat:1,clearcoatRoughness:.03,emissive:0x063b49,emissiveIntensity:.75,transparent:true,opacity:.72}));core.add(outer);
const energy=new THREE.Mesh(new THREE.IcosahedronGeometry(1.28,4),new THREE.MeshPhysicalMaterial({color:0x073d4a,metalness:.3,roughness:.14,clearcoat:1,emissive:0x0795a8,emissiveIntensity:.55,transparent:true,opacity:.3,side:THREE.DoubleSide}));core.add(energy);
const inner=new THREE.Mesh(new THREE.IcosahedronGeometry(.9,3),new THREE.MeshPhysicalMaterial({color:0x17103b,metalness:.45,roughness:.1,clearcoat:1,emissive:0x6429d0,emissiveIntensity:.95,transparent:true,opacity:.38,side:THREE.DoubleSide}));core.add(inner);
const wire=new THREE.Mesh(new THREE.IcosahedronGeometry(1.45,3),new THREE.MeshBasicMaterial({color:0x61efff,wireframe:true,transparent:true,opacity:.18,blending:THREE.AdditiveBlending,depthWrite:false}));core.add(wire);
const innerWire=new THREE.Mesh(new THREE.IcosahedronGeometry(.82,2),new THREE.MeshBasicMaterial({color:0xa77cff,wireframe:true,transparent:true,opacity:.3,blending:THREE.AdditiveBlending,depthWrite:false}));core.add(innerWire);
const nucleus=new THREE.Mesh(new THREE.SphereGeometry(.145,32,32),new THREE.MeshStandardMaterial({color:0xffffff,emissive:0xeaffff,emissiveIntensity:24,roughness:.01}));core.add(nucleus);
const glow=new THREE.Mesh(new THREE.SphereGeometry(.55,32,32),new THREE.MeshBasicMaterial({color:0x61efff,transparent:true,opacity:.09,blending:THREE.AdditiveBlending,depthWrite:false}));core.add(glow);
const halo=new THREE.Mesh(new THREE.SphereGeometry(.98,32,32),new THREE.MeshBasicMaterial({color:0x6355ff,transparent:true,opacity:.025,blending:THREE.AdditiveBlending,depthWrite:false}));core.add(halo);
const filaments=new THREE.Group();core.add(filaments);for(let j=0;j<16;j++){const pts=[];for(let i=0;i<=100;i++){const u=i/100,a=u*Math.PI*2+j*.4,r=.3+.52*Math.sin(u*Math.PI);pts.push(new THREE.Vector3(Math.cos(a)*r,Math.sin(a*1.7+j)*r*.5,Math.sin(a)*r*.8));}filaments.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),new THREE.LineBasicMaterial({color:j%3?0x62efff:0xa77cff,transparent:true,opacity:.28,blending:THREE.AdditiveBlending,depthWrite:false})));}
const streams=[];for(let s=0;s<7;s++){const g=new THREE.Group();core.add(g);const ps=[];for(let i=0;i<120;i++){const m=new THREE.Mesh(new THREE.SphereGeometry(.007+(i%5)*.002,7,7),new THREE.MeshBasicMaterial({color:(i+s)%10===0?0xb58cff:0x62efff,transparent:true,opacity:.25+.55*(i%7)/7,blending:THREE.AdditiveBlending,depthWrite:false}));m.userData={u:i/120,phase:Math.random()*6.28,speed:.5+Math.random()*.7};g.add(m);ps.push(m);}streams.push({g,ps,tilt:s*Math.PI/7,rx:1.6+.1*(s%3),ry:.55+.05*(s%4),rz:.8+.06*(s%5)});}
const bg=new THREE.Group();scene.add(bg);for(let i=0;i<280;i++){const p=new THREE.Mesh(new THREE.SphereGeometry(.003+(i%4)*.0015,6,6),new THREE.MeshBasicMaterial({color:i%12?0x55dfea:0x9b7bff,transparent:true,opacity:.06+(i%5)*.012}));p.position.set((Math.random()-.5)*18,(Math.random()-.5)*10,(Math.random()-.5)*10);bg.add(p);}
const nodeGroup=new THREE.Group();scene.add(nodeGroup);const targets=[[2.6,1.75,.3],[3.35,1.0,.1],[3.5,.05,.2],[3.2,-.9,.15],[2.55,-1.75,.2],[1.45,-2.35,.2],[.15,-2.7,.25]],nodes=[];const ray=new THREE.Raycaster(),mouse=new THREE.Vector2(99,99);let hover=-1;
for(let i=0;i<7;i++){const g=new THREE.Group();g.visible=false;nodeGroup.add(g);const c=i%2?0xa789ff:0x67f4ff;const orb=new THREE.Mesh(new THREE.IcosahedronGeometry(.15,2),new THREE.MeshPhysicalMaterial({color:0x06242e,metalness:.5,roughness:.1,clearcoat:1,emissive:c,emissiveIntensity:7,transparent:true,opacity:0}));g.add(orb);const ring=new THREE.Mesh(new THREE.TorusGeometry(.25,.008,8,72),new THREE.MeshBasicMaterial({color:c,transparent:true,opacity:0,blending:THREE.AdditiveBlending}));g.add(ring);const aura=new THREE.Mesh(new THREE.SphereGeometry(.38,20,20),new THREE.MeshBasicMaterial({color:c,transparent:true,opacity:0,blending:THREE.AdditiveBlending,depthWrite:false}));g.add(aura);const dust=[];for(let k=0;k<30;k++){const q=new THREE.Mesh(new THREE.SphereGeometry(.008+(k%3)*.002,6,6),new THREE.MeshBasicMaterial({color:k%6?0x62efff:0xa789ff,transparent:true,opacity:0,blending:THREE.AdditiveBlending,depthWrite:false}));q.userData={a:k/30*Math.PI*2,r:1.25+.4*(k%7)/7};g.add(q);dust.push(q);}const p=projects[i],label=document.createElement('div');label.className='project-label';label.innerHTML=`<div class="k">${p[1]} / DATA ANALYSIS</div><h3>${p[0]}</h3><div class="d">${p[2]}</div><div class="s">${p[3]}</div>`;$('#labels').appendChild(label);nodes.push({g,orb,ring,aura,dust,label,target:new THREE.Vector3(...targets[i])});}
let px=0,py=0,sx=0,sy=0,scroll=0,targetScroll=0;addEventListener('pointermove',e=>{px=(e.clientX/innerWidth-.5)*2;py=(e.clientY/innerHeight-.5)*2;mouse.set(px,-py)});addEventListener('scroll',()=>{const max=document.documentElement.scrollHeight-innerHeight;targetScroll=max?scrollY/max:0},{passive:true});
const sections=['home','about','work','skills','projects','contact'];$$('.nav').forEach(n=>n.addEventListener('click',()=>{const i=sections.indexOf(n.dataset.section);scrollTo({top:(document.documentElement.scrollHeight-innerHeight)*i/5,behavior:'smooth'})}));
function setSection(s){$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.section===s));['about','work','skills'].forEach(n=>$('#'+n).classList.toggle('active',s===n));$('#hero').classList.toggle('gone',s!=='home');}
function projectP(){return clamp((scroll-.64)/.29)}
function frame(t){requestAnimationFrame(frame);scroll+=(targetScroll-scroll)*.065;sx+=(px-sx)*.055;sy+=(py-sy)*.055;$('#bar').style.width=scroll*100+'%';let s='home';if(scroll>=.166&&scroll<.333)s='about';else if(scroll>=.333&&scroll<.5)s='work';else if(scroll>=.5&&scroll<.64)s='skills';else if(scroll>=.64&&scroll<.93)s='projects';else if(scroll>=.93)s='contact';setSection(s);const inProjects=s==='projects',p=projectP(),active=Math.min(6,Math.floor(p*7));$('#stage').textContent=inProjects?`05 / DATA ANALYSIS / NODE ${String(active+1).padStart(2,'0')}`:(s==='home'?'01 / DATA CORE':s.toUpperCase());$('#readout').textContent=inProjects?`SCROLL / FORM NODE ${String(active+1).padStart(2,'0')}`:`CORE / ${s.toUpperCase()}`;
core.rotation.y+=(sx*.18-core.rotation.y)*.05;core.rotation.x+=(-sy*.13-core.rotation.x)*.05;root.rotation.y+=(sx*.05-root.rotation.y)*.035;root.rotation.x+=(-sy*.035-root.rotation.x)*.035;const pulse=1+.025*Math.sin(t*.0025);core.scale.lerp(new THREE.Vector3(pulse,pulse,pulse),.05);energy.rotation.y+=.0016;energy.rotation.x+=.0005;inner.rotation.y-=.0022;wire.rotation.y-=.001;innerWire.rotation.y+=.0025;filaments.rotation.y+=.0018;nucleus.scale.setScalar(1+.13*Math.sin(t*.006));glow.scale.setScalar(1+.18*Math.sin(t*.004));halo.scale.setScalar(1+.1*Math.sin(t*.003));coreLight.intensity=26+10*Math.hypot(sx,sy)+8*Math.sin(t*.003);cyan.intensity=30+10*Math.hypot(sx,sy);violet.intensity=23+8*Math.hypot(sx,sy);
streams.forEach((st,j)=>{st.g.rotation.set(.42+j*.3,.18+j*.24,st.tilt);st.ps.forEach(q=>{const a=q.userData.u*Math.PI*2+q.userData.phase+t*.00055*q.userData.speed;q.position.set(Math.cos(a)*(st.rx+.06*Math.sin(a*3)),Math.sin(a*2+st.tilt)*st.ry,Math.sin(a)*st.rz);})});bg.rotation.y+=.00008;
if(inProjects){ray.setFromCamera(mouse,camera);const hits=ray.intersectObjects(nodes.map(n=>n.orb));hover=hits.length?nodes.findIndex(n=>n.orb===hits[0].object):-1;}else hover=-1;
nodes.forEach((n,i)=>{n.g.visible=inProjects;if(!inProjects){n.label.style.display='none';return}const raw=clamp((p-i/7)*7*1.35),a=smooth(raw),expanded=hover===i&&raw>.65;n.g.position.lerpVectors(new THREE.Vector3(0,0,0),n.target,a);n.orb.material.opacity=.14+.86*a;n.orb.scale.setScalar((.5+1.05*a)*(expanded?1.45:1));n.ring.material.opacity=.1+.65*a;n.ring.scale.setScalar(expanded?1.35:1);n.ring.rotation.z+=.01;n.ring.rotation.x+=.004;n.aura.material.opacity=.015+.11*a+(expanded?.07:0);const crystallize=smooth(clamp((raw-.12)/.7));n.dust.forEach((q,k)=>{const ang=q.userData.a+t*.0008*(1+k%3),r=q.userData.r*(1-crystallize)+.18*crystallize;q.position.set(Math.cos(ang)*r,Math.sin(ang*1.3)*r*.62,Math.sin(ang)*r*.7);q.material.opacity=.08+.8*crystallize});const reveal=Math.max(i===active?smooth(raw):0,expanded?.98:0);const v=n.g.position.clone().project(camera),x=(v.x*.5+.5)*innerWidth,y=(-v.y*.5+.5)*innerHeight;n.label.style.display=reveal>.01?'block':'none';n.label.style.left=clamp(x+(expanded?42:30),20,innerWidth-470)+'px';n.label.style.top=clamp(y-40,25,innerHeight-210)+'px';n.label.style.opacity=reveal;n.label.style.transform=`translate3d(${(1-reveal)*18}px,${(1-reveal)*6}px,0)`;n.label.classList.toggle('expanded',expanded)});
camera.position.x+=(inProjects?sx*.2:0-camera.position.x)*.035;camera.position.y+=(inProjects?-sy*.12:0-camera.position.y)*.035;camera.position.z+=(10.8-camera.position.z)*.035;camera.lookAt(0,0,0);renderer.render(scene,camera)}requestAnimationFrame(frame);
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});