import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.161.0/build/three.module.js';

const categories=[
{id:'data',name:'DATA ANALYSIS',color:0x67f4ff,projects:[
['Sprocket Central — Customer & Sales Intelligence','01','Customer segmentation, sales performance and insight discovery.','Power BI · Segmentation · Analysis'],
['Credit Card Transaction Analysis','02','Transaction patterns, customer behavior and financial performance.','Power BI · SQL · Data Modeling'],
['COVID-19 Data Analysis','03','A visual exploration of global COVID-19 trends and impact.','Power BI · Trends · Visualization'],
['Company Attrition Analytics','04','Workforce attrition patterns and people-focused business insights.','Power BI · HR Analytics · Insights'],
['Data-Driven Sales Analysis','05','Sales performance analysis focused on commercial decision-making.','Power BI · Forecasting · KPI'],
['Google Play Store Apps Analysis','06','App ecosystem, category and performance analysis.','Power BI · Data Cleaning · App Analytics'],
['Sales Data Analysis','07','Performance trends and actionable business metrics.','Power BI · Excel · Data Analysis']]},
{id:'ai',name:'AI / INTELLIGENCE',color:0xa789ff,projects:[]},{id:'software',name:'SOFTWARE DEVELOPMENT',color:0x67f4ff,projects:[]},{id:'automation',name:'AUTOMATION',color:0xa789ff,projects:[]}];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v)),smooth=t=>t*t*(3-2*t),ease=t=>1-Math.pow(1-t,3);
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(38,innerWidth/innerHeight,.1,100);camera.position.set(0,0,10.8);
const renderer=new THREE.WebGLRenderer({canvas:$('#webgl'),antialias:true,alpha:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.55;scene.background=new THREE.Color(0x01040a);
scene.add(new THREE.AmbientLight(0x3b5268,.28));const key=new THREE.DirectionalLight(0xdffaff,3.2);key.position.set(4,5,7);scene.add(key);const cyanLight=new THREE.PointLight(0x43efff,28,11);cyanLight.position.set(2.6,2.2,3.2);scene.add(cyanLight);const violetLight=new THREE.PointLight(0x865cff,22,10);violetLight.position.set(-2.4,-1.7,2.5);scene.add(violetLight);const coreLight=new THREE.PointLight(0x9dffff,24,5.5);coreLight.position.set(0,0,1.8);scene.add(coreLight);
const root=new THREE.Group();scene.add(root),core=new THREE.Group();root.add(core);
const outer=new THREE.Mesh(new THREE.SphereGeometry(1.42,64,64),new THREE.MeshPhysicalMaterial({color:0x04131c,metalness:.72,roughness:.13,clearcoat:1,clearcoatRoughness:.035,emissive:0x06313d,emissiveIntensity:.7,transparent:true,opacity:.76}));core.add(outer);
const energyShell=new THREE.Mesh(new THREE.IcosahedronGeometry(1.28,4),new THREE.MeshPhysicalMaterial({color:0x062f3b,metalness:.35,roughness:.16,clearcoat:1,emissive:0x08798d,emissiveIntensity:.52,transparent:true,opacity:.27,side:THREE.DoubleSide}));core.add(energyShell);
const violetShell=new THREE.Mesh(new THREE.IcosahedronGeometry(.91,3),new THREE.MeshPhysicalMaterial({color:0x141033,metalness:.4,roughness:.12,clearcoat:1,emissive:0x5a27c8,emissiveIntensity:.8,transparent:true,opacity:.4,side:THREE.DoubleSide}));core.add(violetShell);
const cage=new THREE.Mesh(new THREE.IcosahedronGeometry(1.46,3),new THREE.MeshBasicMaterial({color:0x55eaff,wireframe:true,transparent:true,opacity:.16,blending:THREE.AdditiveBlending,depthWrite:false}));core.add(cage);
const innerCage=new THREE.Mesh(new THREE.IcosahedronGeometry(.82,2),new THREE.MeshBasicMaterial({color:0xa77cff,wireframe:true,transparent:true,opacity:.26,blending:THREE.AdditiveBlending,depthWrite:false}));core.add(innerCage);
const nucleus=new THREE.Mesh(new THREE.SphereGeometry(.14,32,32),new THREE.MeshStandardMaterial({color:0xffffff,emissive:0xe9ffff,emissiveIntensity:22,roughness:.01,metalness:.02}));core.add(nucleus);
const nucleusGlow=new THREE.Mesh(new THREE.SphereGeometry(.52,32,32),new THREE.MeshBasicMaterial({color:0x63efff,transparent:true,opacity:.085,blending:THREE.AdditiveBlending,depthWrite:false}));core.add(nucleusGlow);const nucleusGlow2=new THREE.Mesh(new THREE.SphereGeometry(.95,32,32),new THREE.MeshBasicMaterial({color:0x5b7cff,transparent:true,opacity:.025,blending:THREE.AdditiveBlending,depthWrite:false}));core.add(nucleusGlow2);
const filamentGroup=new THREE.Group();core.add(filamentGroup);for(let j=0;j<14;j++){const pts=[];for(let i=0;i<=100;i++){const u=i/100,a=u*Math.PI*2+j*.44,r=.35+.47*Math.sin(u*Math.PI)*(.7+.18*Math.sin(j));pts.push(new THREE.Vector3(Math.cos(a)*r,Math.sin(a*1.8+j)*r*.48,Math.sin(a)*r*.8));}filamentGroup.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),new THREE.LineBasicMaterial({color:j%3===0?0xa77cff:0x5feeff,transparent:true,opacity:.3,blending:THREE.AdditiveBlending,depthWrite:false})));}
const streams=[];for(let s=0;s<7;s++){const group=new THREE.Group();core.add(group);const particles=[];for(let i=0;i<110;i++){const m=new THREE.Mesh(new THREE.SphereGeometry(.008+(i%5)*.0018,7,7),new THREE.MeshBasicMaterial({color:(i+s)%9===0?0xb58cff:0x62efff,transparent:true,opacity:.28+.48*((i%7)/7),blending:THREE.AdditiveBlending,depthWrite:false}));m.userData={u:i/110,phase:Math.random()*6.28,speed:.35+Math.random()*.8,stream:s};group.add(m);particles.push(m);}streams.push({group,particles,tilt:s*Math.PI/7,phase:s*.77,rx:1.62+.08*(s%3),ry:.58+.05*(s%4),rz:.82+.06*(s%5)});}
const closeParticles=[];for(let i=0;i<70;i++){const m=new THREE.Mesh(new THREE.SphereGeometry(.008+(i%4)*.002,7,7),new THREE.MeshBasicMaterial({color:i%6===0?0xa789ff:0x63f1ff,transparent:true,opacity:.48+.3*(i%5)/5,blending:THREE.AdditiveBlending,depthWrite:false}));core.add(m);closeParticles.push(m);}
const field=new THREE.Group();scene.add(field);for(let i=0;i<300;i++){const p=new THREE.Mesh(new THREE.SphereGeometry(.0035+(i%5)*.0014,6,6),new THREE.MeshBasicMaterial({color:i%13===0?0x9b7bff:0x54dfe9,transparent:true,opacity:.055+(i%6)*.012}));p.position.set((Math.random()-.5)*18,(Math.random()-.5)*10,(Math.random()-.5)*10);p.userData={phase:Math.random()*6.28,drift:(Math.random()-.5)*.001};field.add(p);}
const nodeGroup=new THREE.Group();scene.add(nodeGroup),nodePositions=[[2.45,1.95,.45],[3.35,1.05,.1],[3.45,.05,.3],[3.1,-.95,.15],[2.35,-1.85,.35],[1.3,-2.35,.2],[.05,-2.7,.25]],projectNodes=[];
const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2(99,99);let hoveredNode=-1;
for(let i=0;i<7;i++){const g=new THREE.Group();g.visible=false;nodeGroup.add(g),color=i%2===0?0x67f4ff:0xa789ff;const orb=new THREE.Mesh(new THREE.IcosahedronGeometry(.14,2),new THREE.MeshPhysicalMaterial({color:0x09232e,metalness:.45,roughness:.12,clearcoat:1,emissive:color,emissiveIntensity:5,transparent:true,opacity:0}));g.add(orb);const ring=new THREE.Mesh(new THREE.TorusGeometry(.25,.008,8,64),new THREE.MeshBasicMaterial({color,transparent:true,opacity:0,blending:THREE.AdditiveBlending}));g.add(ring);const halo=new THREE.Mesh(new THREE.SphereGeometry(.38,20,20),new THREE.MeshBasicMaterial({color,transparent:true,opacity:0,blending:THREE.AdditiveBlending,depthWrite:false}));g.add(halo);const micro=[];for(let k=0;k<28;k++){const q=new THREE.Mesh(new THREE.SphereGeometry(.008+(k%3)*.002,6,6),new THREE.MeshBasicMaterial({color:k%7===0?0xa789ff:0x61efff,transparent:true,opacity:0,blending:THREE.AdditiveBlending,depthWrite:false}));q.userData={a:k/28*Math.PI*2,seed:Math.random()*6.28,r:1.15+.42*(k%8)/8};g.add(q);micro.push(q);}const p=categories[0].projects[i],label=document.createElement('div');label.className='project-label';label.innerHTML=`<div class="k">${p[1]} / DATA ANALYSIS</div><h3>${p[0]}</h3><div class="d">${p[2]}</div><div class="s">${p[3]}</div>`;$('#labels').appendChild(label);projectNodes.push({g,orb,ring,halo,micro,label,target:new THREE.Vector3(...nodePositions[i]),index:i});}
let pointerX=0,pointerY=0,sx=0,sy=0,targetScroll=0,scroll=0;addEventListener('pointermove',e=>{pointerX=(e.clientX/innerWidth-.5)*2;pointerY=(e.clientY/innerHeight-.5)*2;pointer.set((e.clientX/innerWidth)*2-1,-(e.clientY/innerHeight)*2+1)});addEventListener('scroll',()=>{const max=document.documentElement.scrollHeight-innerHeight;targetScroll=max?scrollY/max:0},{passive:true});
const sections=['home','about','work','skills','projects','contact'];$$('.nav').forEach(n=>n.addEventListener('click',()=>{const i=sections.indexOf(n.dataset.section);window.scrollTo({top:(document.documentElement.scrollHeight-innerHeight)*(i/5),behavior:'smooth'})}));
function projectProgress(){return clamp((scroll-.64)/.29)}function projectIndex(p){return Math.min(6,Math.floor(p*7))}function projectAmount(p,i){return clamp((p-i/7)/(1/7)*1.6)}
function placeLabel(n,a,expanded){const v=n.g.position.clone().project(camera),x=(v.x*.5+.5)*innerWidth,y=(-v.y*.5+.5)*innerHeight;n.label.style.left=clamp(x+(expanded?42:26),22,innerWidth-470)+'px';n.label.style.top=clamp(y-40,30,innerHeight-220)+'px';n.label.style.opacity=String(a);n.label.style.display=a>.01?'block':'none';n.label.style.transform=`translate3d(${(1-a)*22}px,${(1-a)*8}px,0)`;n.label.classList.toggle('expanded',expanded)}
function setSection(section){$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.section===section));['about','work','skills'].forEach(n=>$('#'+n).classList.toggle('active',section===n));$('#hero').classList.toggle('gone',section!=='home')}
function updateHover(){if(scroll<.64||scroll>.93){hoveredNode=-1;return}raycaster.setFromCamera(pointer,camera);const hits=raycaster.intersectObjects(projectNodes.map(n=>n.orb),false);hoveredNode=hits.length?projectNodes.findIndex(n=>n.orb===hits[0].object):-1}
function frame(t){requestAnimationFrame(frame);scroll+=(targetScroll-scroll)*.065;sx+=(pointerX-sx)*.055;sy+=(pointerY-sy)*.055;$('#bar').style.width=scroll*100+'%';let section='home';if(scroll>=.166&&scroll<.333)section='about';else if(scroll>=.333&&scroll<.5)section='work';else if(scroll>=.5&&scroll<.64)section='skills';else if(scroll>=.64&&scroll<.93)section='projects';else if(scroll>=.93)section='contact';setSection(section);const inProjects=section==='projects',pp=projectProgress(),activeIndex=projectIndex(pp);$('#stage').textContent=inProjects?`05 / DATA ANALYSIS / NODE ${String(activeIndex+1).padStart(2,'0')}`:(section==='home'?'01 / DATA CORE':section.toUpperCase());$('#readout').textContent=inProjects?`SCROLL / FORM NODE ${String(activeIndex+1).padStart(2,'0')}`:`CORE / ${section.toUpperCase()}`;
const hoverEnergy=clamp(Math.hypot(sx,sy)),pulse=1+.025*Math.sin(t*.0025);core.rotation.y+=(sx*.18-core.rotation.y)*.05;core.rotation.x+=(-sy*.13-core.rotation.x)*.05;root.rotation.y+=(sx*.055-root.rotation.y)*.035;root.rotation.x+=(-sy*.035-root.rotation.x)*.035;core.scale.lerp(new THREE.Vector3(pulse,pulse,pulse),.05);energyShell.rotation.y+=.0015;energyShell.rotation.x+=.0005;violetShell.rotation.y-=.0021;violetShell.rotation.z+=.0006;cage.rotation.y-=.0011;cage.rotation.z+=.00035;innerCage.rotation.y+=.0025;filamentGroup.rotation.y+=.0018;filamentGroup.rotation.x+=.0006;nucleus.scale.setScalar(1+.12*Math.sin(t*.006));nucleusGlow.scale.setScalar(1+.18*Math.sin(t*.004));nucleusGlow2.scale.setScalar(1+.1*Math.sin(t*.003));coreLight.intensity=24+hoverEnergy*15+7*Math.sin(t*.003);cyanLight.intensity=28+hoverEnergy*12;violetLight.intensity=22+hoverEnergy*8;
streams.forEach((s,j)=>{s.group.rotation.set(.42+j*.31,.18+j*.24,s.tilt);for(const q of s.particles){const a=q.userData.u*Math.PI*2+q.userData.phase+t*.0005*q.userData.speed;const wobble=Math.sin(a*3+s.phase)*.07;q.position.set(Math.cos(a)*(s.rx+wobble),Math.sin(a*2+s.phase)*s.ry,Math.sin(a)*s.rz)}});closeParticles.forEach((q,i)=>{const a=i/closeParticles.length*Math.PI*2+t*.0008*(1+i%4),r=1+(i%9)*.075;q.position.set(Math.cos(a)*r,Math.sin(a*1.7)*.48,Math.sin(a)*r*.72)});field.children.forEach(p=>{p.position.x+=p.userData.drift;p.rotation.y+=.00025;if(p.position.x>9)p.position.x=-9;if(p.position.x<-9)p.position.x=9});updateHover();
projectNodes.forEach((n,i)=>{n.g.visible=inProjects;n.label.style.display='none';if(!inProjects){n.orb.material.opacity=0;n.ring.material.opacity=0;n.halo.material.opacity=0;return}const raw=projectAmount(pp,i),a=smooth(raw),expand=i===hoveredNode&&raw>.72; n.g.position.lerpVectors(new THREE.Vector3(0,0,0),n.target,a);n.orb.material.opacity=.18+.82*a;n.ring.material.opacity=.12+.62*a;n.halo.material.opacity=.012+.095*a+(expand?.06:0);n.orb.scale.setScalar((.45+.95*a)*(expand?1.35:1));n.ring.scale.setScalar(expand?1.3:1);n.ring.rotation.z+=.008+(expand?.01:0);n.ring.rotation.x+=.004;n.g.rotation.y+=.006;const crystallize=smooth(clamp((raw-.08)/.72));n.micro.forEach((q,k)=>{const ang=q.userData.a+t*.0007*(1+k%3),r=q.userData.r*(1-crystallize)+(.23+(expand?.12:0))*crystallize;q.position.set(Math.cos(ang)*r,Math.sin(ang*1.25)*r*.62,Math.sin(ang)*r*.68);q.material.opacity=.06+.75*crystallize});const reveal=i===activeIndex?smooth(raw):0;placeLabel(n,Math.max(reveal,expand?.94:0),expand)});
const camTargetX=inProjects?sx*.22:0,camTargetY=inProjects?-sy*.14:0;camera.position.x+=(camTargetX-camera.position.x)*.035;camera.position.y+=(camTargetY-camera.position.y)*.035;camera.position.z+=(10.8-camera.position.z)*.035;camera.lookAt(0,0,0);renderer.render(scene,camera)}requestAnimationFrame(frame);addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});